services:
  traefik:
    user: "0:1000"
    image: docker.io/library/traefik:v3.5.3
    container_name: traefik
    ports:
      - 80:80
      - 443:443
      - 25565:25565
      # --> (Optional) Enable Dashboard, don't do in production
      - 8080:8080
      # <--
    volumes:
      - /run/docker.sock:/run/docker.sock:ro
      - ./data/config/:/etc/traefik/:ro
      - ./data/certs/:/var/traefik/certs/:rw
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    networks:
      - frontend
    restart: unless-stopped

networks:
  frontend:
    name: frontend
