services:
  jellyseerr:
    user: "1000:1000"
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Australia/Sydney
      - PORT=5055 #optional
    networks:
      - frontend
      - media_backend
    volumes:
      - ./data/config:/app/config
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://jellyseerr:5055/api/v1/status || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyseerr-https.tls=true"
      - "traefik.http.routers.jellyseerr-https.tls.certresolver=cloudflare"
      - "traefik.http.routers.jellyseerr-https.entrypoints=websecure"
      - "traefik.http.routers.jellyseerr-https.rule=Host(`jellyseerr.rvlt.app`)"
      - "traefik.http.routers.jellyseerr-https.middlewares=authentik@file"
      - "traefik.http.services.jellyseerr.loadbalancer.server.port=5055"
networks:
  frontend:
    external: true
  media_backend:
    external: true